name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Add upstream remote
      run: git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git
    - name: Merge upstream/main
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories --no-ff -m "Merge upstream changes"
    - name: Push to GitHub
      run: git push origin main
